
FUNCTION MATCH_PROBLEM(type_string) RESULT (type_number)

    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number

    ! Problem class
    IF (type_string == "PROBLEM_ELASTICITY_CLASS") THEN
      type_number = CMFE_PROBLEM_ELASTICITY_CLASS
    ELSEIF (type_string == "PROBLEM_FLUID_MECHANICS_CLASS") THEN
      type_number = CMFE_PROBLEM_FLUID_MECHANICS_CLASS
    ELSEIF (type_string == "PROBLEM_ELECTROMAGNETICS_CLASS") THEN
      type_number = CMFE_PROBLEM_ELECTROMAGNETICS_CLASS
    ELSEIF (type_string == "CLASSICAL_FIELD_CLASS") THEN
      type_number = CMFE_PROBLEM_CLASSICAL_FIELD_CLASS
    ELSEIF (type_string == "PROBLEM_BIOELECTRICS_CLASS") THEN
      type_number = CMFE_PROBLEM_BIOELECTRICS_CLASS
    ELSEIF (type_string == "PROBLEM_MODAL_CLASS") THEN
      type_number = CMFE_PROBLEM_MODAL_CLASS
    ELSEIF (type_string == "PROBLEM_FITTING_CLASS") THEN
      type_number = CMFE_PROBLEM_FITTING_CLASS
    ELSEIF (type_string == "PROBLEM_OPTIMISATION_CLASS") THEN
      type_number = CMFE_PROBLEM_OPTIMISATION_CLASS
    ELSEIF (type_string == "PROBLEM_MULTI_PHYSICS_CLASS") THEN
      type_number = CMFE_PROBLEM_MULTI_PHYSICS_CLASS
    ELSEIF (type_string == "PROBLEM_MULTI_PHYSICS_CLASS") THEN
      type_number = CMFE_PROBLEM_MULTI_PHYSICS_CLASS
    ELSEIF (type_string == "PROBLEM_CLASSICAL_FIELD_CLASS") THEN
      type_number = CMFE_PROBLEM_CLASSICAL_FIELD_CLASS
    ELSEIF (type_string == "PROBLEM_NO_CLASS") THEN
      type_number = CMFE_PROBLEM_NO_CLASS
    ELSEIF (type_string == "PROBLEM_FINITE_ELASTICITY_TYPE") THEN
      type_number = CMFE_PROBLEM_FINITE_ELASTICITY_TYPE
    ELSEIF (type_string == "PROBLEM_LAPLACE_EQUATION_TYPE") THEN
      type_number = CMFE_PROBLEM_LAPLACE_EQUATION_TYPE
    ELSEIF (type_string == "PROBLEM_NAVIER_STOKES_EQUATION_TYPE") THEN
      type_number = CMFE_PROBLEM_NAVIER_STOKES_EQUATION_TYPE

    !! Problem subtypes
    ELSEIF (type_string == "PROBLEM_STANDARD_LAPLACE_SUBTYPE") THEN
      type_number =  CMFE_PROBLEM_STANDARD_LAPLACE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT_NAVIER_STOKES_SUBTYPE") THEN
      type_number =  CMFE_PROBLEM_TRANSIENT_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NO_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NO_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STATIC_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STATIC_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LAPLACE_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LAPLACE_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_TRANSIENT_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_ALE_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_ALE_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_PGM_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_PGM_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_OPTIMISED_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_OPTIMISED_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STATIC_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STATIC_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LAPLACE_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LAPLACE_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_TRANSIENT_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT_RBS_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_TRANSIENT_RBS_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MULTISCALE_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MULTISCALE_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT1D_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_TRANSIENT1D_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_COUPLED1D0D_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_COUPLED1D0D_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT1D_ADV_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_TRANSIENT1D_ADV_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_COUPLED1D0D_ADV_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_COUPLED1D0D_ADV_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STREE1D0D_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STREE1D0D_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STREE1D0D_ADV_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STREE1D0D_ADV_SUBTYPE
    ELSEIF (type_string == "PROBLEM_ALE_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_ALE_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_PGM_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_PGM_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_OPTIMISED_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_OPTIMISED_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_QUASISTATIC_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_QUASISTATIC_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_ALE_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_ALE_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_TRANSIENT_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_TRANSIENT_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_PGM_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_PGM_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_PGM_TRANSIENT_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_PGM_TRANSIENT_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_LAPLACE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_LAPLACE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_GENERALISED_LAPLACE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_GENERALISED_LAPLACE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STATIC_POISEUILLE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STATIC_POISEUILLE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_DYNAMIC_POISEUILLE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_DYNAMIC_POISEUILLE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_EXTRACELLULAR_BIDOMAIN_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_EXTRACELLULAR_BIDOMAIN_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_ALE_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_ALE_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_FITTED_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_FITTED_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_HELMHOLTZ_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_HELMHOLTZ_SUBTYPE
    ELSEIF (type_string == "PROBLEM_GENERALISED_HELMHOLTZ_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_GENERALISED_HELMHOLTZ_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NO_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NO_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NO_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NO_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NO_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NO_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NO_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NO_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NO_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NO_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LINEAR_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LINEAR_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "PROBLEM_NONLINEAR_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_NONLINEAR_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STATIC_BURGERS_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STATIC_BURGERS_SUBTYPE
    ELSEIF (type_string == "PROBLEM_DYNAMIC_BURGERS_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_DYNAMIC_BURGERS_SUBTYPE
    ELSEIF (type_string == "PROBLEM_CELLML_REAC_INTEG_REAC_DIFF_STRANG_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_CELLML_REAC_INTEG_REAC_DIFF_STRANG_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_CELLML_REAC_EVAL_REAC_DIFF_NO_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_CELLML_REAC_EVAL_REAC_DIFF_NO_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_CONSTANT_REAC_DIFF_NO_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_CONSTANT_REAC_DIFF_NO_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_DATA_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_DATA_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_VECTOR_DATA_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_VECTOR_DATA_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_DIV_FREE_VECTOR_DATA_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_DIV_FREE_VECTOR_DATA_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_DATA_POINT_VECTOR_STATIC_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_DATA_POINT_VECTOR_STATIC_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_DATA_PT_VECTOR_QUASISTATIC_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_DATA_PT_VECTOR_QUASISTATIC_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_DIV_FREE_VECTOR_DATA_PRE_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_DIV_FREE_VECTOR_DATA_PRE_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_GENERALISED_DATA_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_GENERALISED_DATA_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MAT_PROPERTIES_DATA_FITTING_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MAT_PROPERTIES_DATA_FITTING_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_ELASTICITY_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_ELASTICITY_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_PGM_ELASTICITY_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_PGM_ELASTICITY_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_QUASISTATIC_ELASTICITY_TRANSIENT_DARCY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_QUASISTATIC_ELASTICITY_TRANSIENT_DARCY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_QUASISTATIC_ELAST_TRANS_DARCY_MAT_SOLVE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_QUASISTATIC_ELAST_TRANS_DARCY_MAT_SOLVE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_COUPLED_SOURCE_DIFFUSION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_COUPLED_SOURCE_DIFFUSION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_COUPLED_SOURCE_DIFFUSION_ADVEC_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_COUPLED_SOURCE_DIFFUSION_ADVEC_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_MULTI_COMPARTMENT_TRANSPORT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_MULTI_COMPARTMENT_TRANSPORT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_STANDARD_ELASTICITY_FLUID_PRESSURE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_STANDARD_ELASTICITY_FLUID_PRESSURE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_GUDUNOV_MONODOMAIN_SIMPLE_ELASTICITY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_GUDUNOV_MONODOMAIN_SIMPLE_ELASTICITY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_GUDUNOV_MONODOMAIN_1D3D_ELASTICITY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_GUDUNOV_MONODOMAIN_1D3D_ELASTICITY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MONODOMAIN_ELASTICITY_W_TITIN_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MONODOMAIN_ELASTICITY_W_TITIN_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MONODOMAIN_ELASTICITY_VELOCITY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MONODOMAIN_ELASTICITY_VELOCITY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_FINITE_ELASTICITY_NAVIER_STOKES_ALE_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_FINITE_ELASTICITY_NAVIER_STOKES_ALE_SUBTYPE
    ELSEIF (type_string == "PROBLEM_QUASISTATIC_FINITE_ELASTICITY_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_QUASISTATIC_FINITE_ELASTICITY_SUBTYPE
    ELSEIF (type_string == "PROBLEM_FINITE_ELASTICITY_CELLML_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_FINITE_ELASTICITY_CELLML_SUBTYPE
    ELSEIF (type_string == "PROBLEM_FINITE_ELASTICITY_WITH_GROWTH_CELLML_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_FINITE_ELASTICITY_WITH_GROWTH_CELLML_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MONODOMAIN_GUDUNOV_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MONODOMAIN_GUDUNOV_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MONODOMAIN_STRANG_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MONODOMAIN_STRANG_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_BIDOMAIN_GUDUNOV_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_BIDOMAIN_GUDUNOV_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_BIDOMAIN_STRANG_SPLIT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_BIDOMAIN_STRANG_SPLIT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MONODOMAIN_BUENOOROVIO_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MONODOMAIN_BUENOOROVIO_SUBTYPE
    ELSEIF (type_string == "PROBLEM_MONODOMAIN_TENTUSSCHER06_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_MONODOMAIN_TENTUSSCHER06_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LE_CONTACT_TRANSFORM_REPROJECT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LE_CONTACT_TRANSFORM_REPROJECT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LE_CONTACT_TRANSFORM_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LE_CONTACT_TRANSFORM_SUBTYPE
    ELSEIF (type_string == "PROBLEM_LE_CONTACT_REPROJECT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_LE_CONTACT_REPROJECT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_FE_CONTACT_TRANSFORM_REPROJECT_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_FE_CONTACT_TRANSFORM_REPROJECT_SUBTYPE
    ELSEIF (type_string == "PROBLEM_FE_CONTACT_TRANSFORM_SUBTYPE") THEN
      type_number = CMFE_PROBLEM_FE_CONTACT_TRANSFORM_SUBTYPE
    ELSE
      CALL HANDLE_ERROR("Invalid problem type argument "// type_string // "in subroutine MATCH_PROBLEM()")
    ENDIF

END FUNCTION

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.DEFINES MESH TYPE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION MATCH_GENERATED_MESH(type_string) RESULT (type_number)
    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number
    ! number of dimensions
    IF (type_string == "GENERATED_MESH_1D") THEN
      type_number = 1
    ELSEIF (type_string == "GENERATED_MESH_2D") THEN
      type_number = 2
    ELSEIF (type_string == "GENERATED_MESH_3D") THEN
      type_number = 3
    ! generated mesh type
    ELSEIF (type_string == "GENERATED_REGULAR_MESH_TYPE") THEN
      type_number = CMFE_GENERATED_MESH_REGULAR_MESH_TYPE
    ELSEIF (type_string == "GENERATED_POLAR_MESH_TYPE") THEN
      type_number = CMFE_GENERATED_MESH_POLAR_MESH_TYPE
    ELSEIF (type_string == "GENERATED_TREE_MESH_TYPE") THEN
      type_number = CMFE_GENERATED_MESH_FRACTAL_TREE_MESH_TYPE
    ELSEIF (type_string == "GENERATED_CYLINDER_MESH_TYPE") THEN
      type_number = CMFE_GENERATED_MESH_CYLINDER_MESH_TYPE
    ELSEIF (type_string == "GENERATED_ELLIPSOID_MESH_TYPE") THEN
      type_number = CMFE_GENERATED_MESH_ELLIPSOID_MESH_TYPE
    ELSE
      CALL HANDLE_ERROR("Invalid mesh argument  "//type_string // "in subroutine MATCH_GENERATED_MESH()" )
    ENDIF
END FUNCTION

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.REMOVES INTERPOLATION TYPE FOR STATE VARIABLE!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION MATCH_BASIS(type_string) RESULT (type_number)

    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number
    SELECT CASE (type_string)
    case("LINEAR_LAGRANGE_INTERPOLATION")
      type_number=CMFE_BASIS_LINEAR_LAGRANGE_INTERPOLATION
    case("QUADRATIC_LAGRANGE_INTERPOLATION")
      type_number=CMFE_BASIS_QUADRATIC_LAGRANGE_INTERPOLATION
    case("CUBIC_LAGRANGE_INTERPOLATION ")
      type_number=CMFE_BASIS_QUADRATIC_LAGRANGE_INTERPOLATION
    case("QUADRATIC1_HERMITE_INTERPOLATION")
      type_number=CMFE_BASIS_QUADRATIC1_HERMITE_INTERPOLATION
    case("CUBIC_HERMITE_INTERPOLATION")
      type_number=CMFE_BASIS_CUBIC_HERMITE_INTERPOLATION
    case("QUADRATIC2_HERMITE_INTERPOLATION")
      type_number=CMFE_BASIS_QUADRATIC2_HERMITE_INTERPOLATION
    case("LINEAR_SIMPLEX_INTERPOLATION")
      type_number=CMFE_BASIS_LINEAR_SIMPLEX_INTERPOLATION
    case("QUADRATIC_SIMPLEX_INTERPOLATION")
      type_number=CMFE_BASIS_QUADRATIC_SIMPLEX_INTERPOLATION
    case("CUBIC_SIMPLEX_INTERPOLATION")
      type_number=CMFE_BASIS_CUBIC_SIMPLEX_INTERPOLATION
    case("BASIS_LAGRANGE_HERMITE_TP_TYPE")
      type_number=CMFE_BASIS_LAGRANGE_HERMITE_TP_TYPE
    case("CMFE_BASIS_SERENDIPITY_TYPE")
      type_number=CMFE_BASIS_SERENDIPITY_TYPE
    case("BASIS_SIMPLEX_TYPE")
      type_number=CMFE_BASIS_SIMPLEX_TYPE
    case("BASIS_AUXILLIARY_TYPE")
      type_number=CMFE_BASIS_AUXILLIARY_TYPE
    case("BASIS_B_SPLINE_TP_TYPE")
      type_number=CMFE_BASIS_B_SPLINE_TP_TYPE
    case("BASIS_FOURIER_LAGRANGE_HERMITE_TP_TYPE")
      type_number=CMFE_BASIS_FOURIER_LAGRANGE_HERMITE_TP_TYPE
    case("BASIS_EXTENDED_LAGRANGE_TP_TYPE")
      type_number=CMFE_BASIS_EXTENDED_LAGRANGE_TP_TYPE
    END SELECT

END FUNCTION


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.DEFINES COORDINATE SYSTEM !!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION MATCH_COORDINATE_SYSTEM(type_string) RESULT (type_number)

    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number

    IF (type_string == "COORDINATE_RECTANGULAR_CARTESIAN_TYPE") THEN
      type_number = CMFE_COORDINATE_RECTANGULAR_CARTESIAN_TYPE
    ELSEIF (type_string == "COORDINATE_CYLINDRICAL_POLAR_TYPE") THEN
      type_number = CMFE_COORDINATE_CYLINDRICAL_POLAR_TYPE
    ELSEIF (type_string == "COORDINATE_SPHERICAL_POLAR_TYPE") THEN
      type_number = CMFE_COORDINATE_SPHERICAL_POLAR_TYPE
    ELSEIF (type_string == "COORDINATE_PROLATE_SPHEROIDAL_TYPE") THEN
      type_number = CMFE_COORDINATE_PROLATE_SPHEROIDAL_TYPE
    ELSEIF (type_string == "COORDINATE_OBLATE_SPHEROIDAL_TYPE") THEN
      type_number = CMFE_COORDINATE_OBLATE_SPHEROIDAL_TYPE

    !! Dimensions of the coordinate system
    ELSEIF (type_string == "COORDINATE_SYSTEM_1D") THEN
      type_number = 1
    ELSEIF (type_string == "COORDINATE_SYSTEM_2D") THEN
      type_number = 2
    ELSEIF (type_string == "COORDINATE_SYSTEM_3D") THEN
      type_number = 3
    ELSE

      CALL HANDLE_ERROR("Invalid coordinate system argument  "//type_string)

    ENDIF

END FUNCTION

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.REMOVES INTERPOLATION TYPE FOR STATE VARIABLE!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION MATCH_EQUATION_SET(type_string) RESULT (type_number)

    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number

    ! EQUATIONS_SET_CLASS
    IF (type_string == "EQUATIONS_SET_ELASTICITY_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_ELASTICITY_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_CLASSICAL_FIELD_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_CLASSICAL_FIELD_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_FLUID_MECHANICS_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_FLUID_MECHANICS_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_FITTING_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_FITTING_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_MODAL_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_MODAL_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_MULTI_PHYSICS_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_MULTI_PHYSICS_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_NO_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_NO_CLASS
    ELSEIF (type_string == "EQUATIONS_SET_OPTIMISATION_CLASS") THEN
      type_number = CMFE_EQUATIONS_SET_OPTIMISATION_CLASS
    ELSEIF (type_string == "PROBLEM_BIOELECTRICS_CLASS") THEN
      type_number = CMFE_PROBLEM_BIOELECTRICS_CLASS
    ! TODO insert more classes.. TODO

    ! EQUATIONS_SET_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_ELASTICITY_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_ELASTICITY_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_FINITE_ELASTICITY_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_FINITE_ELASTICITY_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_STOKES_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STOKES_EQUATION_TYPE
   ELSEIF (type_string == "EQUATIONS_SET_NAVIER_STOKES_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NAVIER_STOKES_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_DARCY_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DARCY_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_DARCY_PRESSURE_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DARCY_PRESSURE_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_POISEUILLE_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_POISEUILLE_EQUATION_TYPE
   ELSEIF (type_string == "EQUATIONS_SET_BURGERS_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_BURGERS_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_CHARACTERISTIC_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CHARACTERISTIC_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_ELECTROSTATIC_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ELECTROSTATIC_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_MAGNETOSTATIC_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MAGNETOSTATIC_TYPE
   ELSEIF (type_string == "EQUATIONS_SET_LAPLACE_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LAPLACE_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_POISSON_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_POISSON_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_HELMHOLTZ_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_HELMHOLTZ_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_WAVE_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_WAVE_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_DIFFUSION_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DIFFUSION_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_ADVECTION_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ADVECTION_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_ADVECTION_DIFFUSION_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ADVECTION_DIFFUSION_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_REACTION_DIFFUSION_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_REACTION_DIFFUSION_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_BIHARMONIC_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_BIHARMONIC_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_MONODOMAIN_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MONODOMAIN_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_BIDOMAIN_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_BIDOMAIN_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_ELASTIC_MODAL_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_ELASTIC_MODAL_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_ELASTIC_MODAL_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_ELASTIC_MODAL_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_ELASTIC_MODAL_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_ELASTIC_MODAL_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_DATA_FITTING_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DATA_FITTING_EQUATION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_FINITE_ELASTICITY_DARCY_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_FINITE_ELASTICITY_DARCY_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_FINITE_ELASTICITY_STOKES_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_FINITE_ELASTICITY_STOKES_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_FINITE_ELASTICITY_NAVIER_STOKES_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_FINITE_ELASTICITY_NAVIER_STOKES_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_DIFFUSION_DIFFUSION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DIFFUSION_DIFFUSION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_DIFFUSION_ADVECTION_DIFFUSION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DIFFUSION_ADVECTION_DIFFUSION_TYPE
    ELSEIF (type_string == "EQUATIONS_SET_MONODOMAIN_STRANG_SPLITTING_EQUATION_TYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MONODOMAIN_STRANG_SPLITTING_EQUATION_TYPE


    ! EQUATIONS_SET_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_THREE_DIMENSIONAL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_THREE_DIMENSIONAL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TWO_DIMENSIONAL_PLANE_STRESS_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TWO_DIMENSIONAL_PLANE_STRESS_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TWO_DIMENSIONAL_PLANE_STRAIN_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TWO_DIMENSIONAL_PLANE_STRAIN_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ONE_DIMENSIONAL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ONE_DIMENSIONAL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_PLATE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_PLATE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_SHELL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_SHELL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MOONEY_RIVLIN_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MOONEY_RIVLIN_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_INCOMPRESSIBLE_MOONEY_RIVLIN_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_INCOMPRESSIBLE_MOONEY_RIVLIN_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NEARLY_INCOMPRESSIBLE_MOONEY_RIVLIN_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NEARLY_INCOMPRESSIBLE_MOONEY_RIVLIN_SUBTYPE
    ELSEIF (type_string == "CMFE_EQUATIONS_SET_MOONEY_RIVLIN_ACTIVECONTRACTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MOONEY_RIVLIN_ACTIVECONTRACTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STVENANT_KIRCHOFF_ACTIVECONTRACTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STVENANT_KIRCHOFF_ACTIVECONTRACTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ACTIVECONTRACTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ACTIVECONTRACTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ISOTROPIC_EXPONENTIAL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ISOTROPIC_EXPONENTIAL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSVERSE_ISOTROPIC_EXPONENTIAL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSVERSE_ISOTROPIC_EXPONENTIAL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSVERSE_ISOTROPIC_ACTIVE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSVERSE_ISOTROPIC_ACTIVE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANS_ISOTROPIC_ACTIVE_TRANSITION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANS_ISOTROPIC_ACTIVE_TRANSITION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANS_ISOTROPIC_ACTIVE_TRANSITION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANS_ISOTROPIC_ACTIVE_TRANSITION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_COMPRESSIBLE_FINITE_ELASTICITY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_COMPRESSIBLE_FINITE_ELASTICITY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_COMPRESSIBLE_ACTIVECONTRACTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_COMPRESSIBLE_ACTIVECONTRACTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSVERSE_ISOTROPIC_GUCCIONE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSVERSE_ISOTROPIC_GUCCIONE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_GUCCIONE_ACTIVECONTRACTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_GUCCIONE_ACTIVECONTRACTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_INCOMPRESS_FINITE_ELASTICITY_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_INCOMPRESS_FINITE_ELASTICITY_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ELASTICITY_DARCY_INRIA_MODEL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ELASTICITY_DARCY_INRIA_MODEL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ELASTICITY_MULTI_COMP_DARCY_INRIA_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ELASTICITY_MULTI_COMP_DARCY_INRIA_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_INCOMPRESS_ELASTICITY_DRIVEN_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_INCOMPRESS_ELASTICITY_DRIVEN_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_INCOMPRESSIBLE_ELASTICITY_DRIVEN_MR_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_INCOMPRESSIBLE_ELASTICITY_DRIVEN_MR_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_INCOMPRESS_ELAST_MULTI_COMP_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_INCOMPRESS_ELAST_MULTI_COMP_DARCY_SUBTYPE
    ELSEIF (type_string == "CMFE_EQUATIONS_SET_MEMBRANE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MEMBRANE_SUBTYPE
    ELSEIF (type_string == "CMFE_EQUATIONS_SET_ORTHOTROPIC_HOLZAPFEL_OGDEN_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ORTHOTROPIC_HOLZAPFEL_OGDEN_SUBTYPE
    ELSEIF (type_string == "CMFE_EQUATIONS_SET_HOLZAPFEL_OGDEN_ACTIVECONTRACTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_HOLZAPFEL_OGDEN_ACTIVECONTRACTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ELASTICITY_FLUID_PRES_STATIC_INRIA_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ELASTICITY_FLUID_PRES_STATIC_INRIA_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ELASTICITY_FLUID_PRES_HOLMES_MOW_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ELASTICITY_FLUID_PRES_HOLMES_MOW_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSVERSE_ISOTROPIC_POLYNOMIAL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSVERSE_ISOTROPIC_POLYNOMIAL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ANISOTROPIC_POLYNOMIAL_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ANISOTROPIC_POLYNOMIAL_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ANISOTROPIC_POLYNOMIAL_ACTIVE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ANISOTROPIC_POLYNOMIAL_ACTIVE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSVERSE_ISOTROPIC_HUMPHREY_YIN_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSVERSE_ISOTROPIC_HUMPHREY_YIN_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STATIC_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STATIC_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LAPLACE_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LAPLACE_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ALE_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ALE_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_PGM_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_PGM_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_OPTIMISED_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_OPTIMISED_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STATIC_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STATIC_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LAPLACE_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LAPLACE_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "TRANSIENT_RBS_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT_RBS_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STATIC_RBS_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STATIC_RBS_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT1D_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT1D_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT1D_ADV_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT1D_ADV_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CHARACTERISTIC_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CHARACTERISTIC_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_COUPLED1D0D_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_COUPLED1D0D_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_COUPLED1D0D_ADV_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_COUPLED1D0D_ADV_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STREE1D0D_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STREE1D0D_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STREE1D0D_ADV_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STREE1D0D_ADV_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ALE_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ALE_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_PGM_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_PGM_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_OPTIMISED_NAVIER_STOKES_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_OPTIMISED_NAVIER_STOKES_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STANDARD_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STANDARD_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUASISTATIC_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUASISTATIC_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ALE_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ALE_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT_ALE_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_TRANSIENT_ALE_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MULTI_COMPARTMENT_DARCY_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MULTI_COMPARTMENT_DARCY_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_BURGERS_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_BURGERS_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_GENERALISED_BURGERS_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_GENERALISED_BURGERS_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STATIC_BURGERS_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STATIC_BURGERS_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_INVISCID_BURGERS_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_INVISCID_BURGERS_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STANDARD_LAPLACE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STANDARD_LAPLACE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_GENERALISED_LAPLACE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_GENERALISED_LAPLACE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MOVING_MESH_LAPLACE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MOVING_MESH_LAPLACE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STATIC_POISEUILLE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STATIC_POISEUILLE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_DYNAMIC_POISEUILLE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_DYNAMIC_POISEUILLE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NONLINEAR_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NONLINEAR_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ALE_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ALE_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_FITTED_PRESSURE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_FITTED_PRESSURE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXTRACELLULAR_BIDOMAIN_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXTRACELLULAR_BIDOMAIN_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXPONENTIAL_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXPONENTIAL_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXPONENTIAL_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXPONENTIAL_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MULTI_COMP_TRANSPORT_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MULTI_COMP_TRANSPORT_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "CMFE_EQUATIONS_SET_ADVECTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ADVECTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXPONENTIAL_SOURCE_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXPONENTIAL_SOURCE_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTITUTIVE_LAW_IN_CELLML_EVALUATE_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTITUTIVE_LAW_IN_CELLML_EVALUATE_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTITUTIVE_AND_GROWTH_LAW_IN_CELLML_SUBTYPE") THEN
    !  type_number = CMFE_EQUATIONS_SET_CONSTITUTIVE_AND_GROWTH_LAW_IN_CELLML_SUBTYPE ! check this one later
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
    !  type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
    !  type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
    !  type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXP_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXP_SOURCE_ALE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_STATIC_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_ADVECTION_DIFF_SUPG_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_ADVECTION_DIFF_SUPG_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_ADVECTION_DIFF_SUPG_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_ADVECTION_DIFF_SUPG_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LIN_SOURCE_STATIC_ADVEC_DIFF_SUPG_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LIN_SOURCE_STATIC_ADVEC_DIFF_SUPG_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_COUPLED_SOURCE_DIFFUSION_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_COUPLED_SOURCE_DIFFUSION_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_COUPLED_SOURCE_DIFFUSION_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_COUPLED_SOURCE_DIFFUSION_ADVEC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MULT_COMP_TRANSPORT_ADVEC_DIFF_SUPG_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MULT_COMP_TRANSPORT_ADVEC_DIFF_SUPG_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CELLML_REAC_SPLIT_REAC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CELLML_REAC_SPLIT_REAC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CELLML_REAC_NO_SPLIT_REAC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CELLML_REAC_NO_SPLIT_REAC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_REAC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_REAC_DIFF_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MONODOMAIN_BUENOOROVIO_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MONODOMAIN_BUENOOROVIO_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXPONENTIAL_SOURCE_POISSON_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXPONENTIAL_SOURCE_POISSON_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_STANDARD_HELMHOLTZ_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_EXPONENTIAL_SOURCE_ALE_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_EXPONENTIAL_SOURCE_ALE_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_MULTI_COMP_TRANSPORT_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_MULTI_COMP_TRANSPORT_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_ADVECTION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_ADVECTION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_NO_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_NO_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_CONSTANT_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_CONSTANT_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_LINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_LINEAR_SOURCE_ADVECTION_DIFFUSION_SUBTYPE
    ELSEIF (type_string == "EQUATIONS_SET_QUADRATIC_SOURCE_ADVEC_DIFF_SUBTYPE") THEN
      type_number = CMFE_EQUATIONS_SET_QUADRATIC_SOURCE_ADVEC_DIFF_SUBTYPE
    ELSE
      CALL HANDLE_ERROR("Invalid  argument "//type_string// "in subroutine MATCH_EQUATION_SET() ")
    ENDIF

END FUNCTION

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.READS KEYWORDDS TO DEFINE the OUTPUT!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!OF THE ANALYSIS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


FUNCTION MATCH_OUTPUT(type_string) RESULT (type_number)

    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number
    ! the way matrices are stored
    IF (type_string == "EQUATIONS_SPARSE_MATRICES") THEN
      type_number = CMFE_EQUATIONS_SPARSE_MATRICES
    ELSEIF (type_string == "EQUATIONS_FULL_MATRICES") THEN
      type_number = CMFE_EQUATIONS_FULL_MATRICES
    ! output type
    ELSEIF (type_string == "EQUATIONS_NO_OUTPUT") THEN
      type_number = CMFE_EQUATIONS_NO_OUTPUT
    ELSEIF (type_string == "EQUATIONS_TIMING_OUTPUT") THEN
      type_number = CMFE_EQUATIONS_TIMING_OUTPUT
    ELSEIF (type_string == "EQUATIONS_MATRIX_OUTPUT") THEN
      type_number = CMFE_EQUATIONS_MATRIX_OUTPUT
    ELSEIF (type_string == "EQUATIONS_ELEMENT_MATRIX_OUTPUT") THEN
      type_number = CMFE_EQUATIONS_ELEMENT_MATRIX_OUTPUT
    ELSEIF (type_string == "SOLVER_PROGRESS_OUTPUT") THEN
      type_number = CMFE_SOLVER_PROGRESS_OUTPUT
    ELSE
      CALL HANDLE_ERROR("Invalid argument  "//type_string//  " in MATCH_OUTPUT subroutine")
    ENDIF
END FUNCTION


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.READS KEYWORDDS TO DEFINE the depENDent field!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION match_variable_type(type_string) RESULT (type_number)
    character(*), intent(in) :: type_string
    integer                  :: type_number
    IF (type_string == "FIELD_U_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_NUMBER_OF_VARIABLE_SUBTYPES
    ELSEIF (type_string == "FIELD_U_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_U_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELUDELN_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELUDELN_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELUDELT_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELUDELT_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DEL2UDELT2_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DEL2UDELT2_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_V_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_V_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELVDELN_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELVDELN_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELVDELT_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELVDELT_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DEL2VDELT2_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DEL2VDELT2_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_U1_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_U1_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU1DELN_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU1DELN_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU1DELT_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU1DELT_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DEL2U1DELT2_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DEL2U1DELT2_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_U1_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_U1_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU1DELN_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU1DELN_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU1DELT_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU1DELT_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DEL2U1DELT2_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DEL2U1DELT2_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_U2_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_U2_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU2DELN_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU2DELT_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU2DELT_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU2DELT_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DEL2U2DELT2_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DEL2U2DELT2_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_U3_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_U3_VARIABLE_TYPE
    ELSEIF (type_string == "FIELD_DELU3DELN_VARIABLE_TYPE") THEN
      type_number = CMFE_FIELD_DELU3DELN_VARIABLE_TYPE

    END IF

END FUNCTION match_variable_type


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.READS KEYWORDDS TO DEFINE BCs!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION MATCH_BC(type_string) RESULT (type_number)
    character(*), intent(in) :: type_string
    integer                :: type_number
    !! surfaces of  generated regular mesh
     IF  (type_string == "MESH_REGULAR_RIGHT_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_RIGHT_SURFACE
     ELSEIF (type_string == "MESH_REGULAR_LEFT_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_LEFT_SURFACE
     ELSEIF (type_string == "REGULAR_FRONT_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_FRONT_SURFACE
     ELSEIF (type_string == "MESH_REGULAR_BOTTOM_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_BOTTOM_SURFACE
     ELSEIF (type_string == "MESH_REGULAR_FRONT_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_FRONT_SURFACE
     ELSEIF (type_string == "MESH_REGULAR_BACK_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_BACK_SURFACE
     ELSEIF (type_string == "MESH_REGULAR_TOP_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_REGULAR_TOP_SURFACE
    !! surfaces of  generated cylindrical mesh
     ELSEIF  (type_string == "MESH_CYLINDER_INNER_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_CYLINDER_INNER_SURFACE
     ELSEIF (type_string == "MESH_CYLINDER_OUTER_SURFACE ") THEN
       type_number = CMFE_GENERATED_MESH_CYLINDER_OUTER_SURFACE
     ELSEIF (type_string == "MESH_CYLINDER_TOP_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_CYLINDER_TOP_SURFACE
     ELSEIF (type_string == "MESH_CYLINDER_BOTTOM_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_CYLINDER_BOTTOM_SURFACE
    !! surfaces of  generated ellipsoidal mesh
     ELSEIF (type_string == "MESH_ELLIPSOID_INNER_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_ELLIPSOID_INNER_SURFACE
     ELSEIF (type_string == "MESH_ELLIPSOID_OUTER_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_ELLIPSOID_OUTER_SURFACE
     ELSEIF (type_string == "MESH_ELLIPSOID_TOP_SURFACE") THEN
       type_number = CMFE_GENERATED_MESH_ELLIPSOID_TOP_SURFACE
    !! types of BCs
     ELSEIF (type_string == "BOUNDARY_CONDITION_FREE") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FREE
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_WALL") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_WALL
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_INLET") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_INLET
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_OUTLET") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_OUTLET
     ELSEIF (type_string == "BOUNDARY_CONDITION_MOVED_WALL") THEN
       type_number = CMFE_BOUNDARY_CONDITION_MOVED_WALL
     ELSEIF (type_string == "BOUNDARY_CONDITION_MOVED_WALL_INCREMENTED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_MOVED_WALL_INCREMENTED
     ELSEIF (type_string == "BOUNDARY_CONDITION_FREE_WALL") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FREE_WALL
     ELSEIF (type_string == "BOUNDARY_CONDITION_NEUMANN_POINT") THEN
       type_number = CMFE_BOUNDARY_CONDITION_NEUMANN_POINT
     ELSEIF (type_string == "BOUNDARY_CONDITION_NEUMANN_POINT_INCREMENTED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_NEUMANN_POINT_INCREMENTED
     ELSEIF (type_string == "BOUNDARY_CONDITION_NEUMANN_INTEGRATED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_NEUMANN_INTEGRATED
     ELSEIF (type_string == "BOUNDARY_CONDITION_DIRICHLET") THEN
       type_number = CMFE_BOUNDARY_CONDITION_DIRICHLET
     ELSEIF (type_string == "BOUNDARY_CONDITION_CAUCHY") THEN
       type_number = CMFE_BOUNDARY_CONDITION_CAUCHY
     ELSEIF (type_string == "BOUNDARY_CONDITION_ROBIN") THEN
       type_number = CMFE_BOUNDARY_CONDITION_ROBIN
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_INCREMENTED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_INCREMENTED
     ELSEIF (type_string == "BOUNDARY_CONDITION_PRESSURE") THEN
       type_number = CMFE_BOUNDARY_CONDITION_PRESSURE
     ELSEIF (type_string == "BOUNDARY_CONDITION_PRESSURE_INCREMENTED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_PRESSURE_INCREMENTED
     ELSEIF (type_string == "BOUNDARY_CONDITION_CORRECTION_MASS_INCREASE") THEN
       type_number = CMFE_BOUNDARY_CONDITION_CORRECTION_MASS_INCREASE
     ELSEIF (type_string == "BOUNDARY_CONDITION_IMPERMEABLE_WALL") THEN
       type_number = CMFE_BOUNDARY_CONDITION_IMPERMEABLE_WALL
     ELSEIF (type_string == "BOUNDARY_CONDITION_NEUMANN_INTEGRATED_ONLY") THEN
       type_number = CMFE_BOUNDARY_CONDITION_NEUMANN_INTEGRATED_ONLY
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_FITTED") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_FITTED
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_NONREFLECTING") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_NONREFLECTING
     ELSEIF (type_string == "BOUNDARY_CONDITION_FIXED_CELLML") THEN
       type_number = CMFE_BOUNDARY_CONDITION_FIXED_CELLML
     ELSE
       CALL HANDLE_ERROR( type_string // " is an invalid boundary condition argument in subroutine MATCH_BC(),  ")

     END IF
END FUNCTION MATCH_BC


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.READS KEYWORDDS TO DEFINE SOLVER!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION MATCH_SOLVER(type_string) RESULT (type_number)
    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number
    !!!! solvers for evaluating set of equations
    IF (type_string == "SOLVER_LINEAR_DIRECT_SOLVE_TYPE") THEN
      type_number = CMFE_SOLVER_LINEAR_DIRECT_SOLVE_TYPE
    ELSEIF (type_string == "SOLVER_LINEAR_ITERATIVE_SOLVE_TYPE") THEN
      type_number = CMFE_SOLVER_LINEAR_ITERATIVE_SOLVE_TYPE
    !!!! types of linear direct solvers
    ELSEIF (type_string == "SOLVER_DIRECT_LU") THEN
      type_number = CMFE_SOLVER_DIRECT_LU
    ELSEIF (type_string == "SOLVER_DIRECT_CHOLESKY") THEN
      type_number = CMFE_SOLVER_DIRECT_CHOLESKY
    ELSEIF (type_string == "SOLVER_DIRECT_SVD") THEN
      type_number = CMFE_SOLVER_DIRECT_SVD
    !!!! types of linear iterative solvers
    ELSEIF (type_string == "SOLVER_ITERATIVE_RICHARDSON") THEN
      type_number = CMFE_SOLVER_ITERATIVE_RICHARDSON
    ELSEIF (type_string == "SOLVER_ITERATIVE_CHEBYSHEV") THEN
      type_number = CMFE_SOLVER_ITERATIVE_CHEBYSHEV
    ELSEIF (type_string == "SOLVER_ITERATIVE_CONJUGATE_GRADIENT") THEN
      type_number = CMFE_SOLVER_ITERATIVE_CONJUGATE_GRADIENT
    ELSEIF (type_string == "SOLVER_ITERATIVE_BICONJUGATE_GRADIENT") THEN
      type_number = CMFE_SOLVER_ITERATIVE_BICONJUGATE_GRADIENT
    ELSEIF (type_string == "SOLVER_ITERATIVE_GMRES") THEN
      type_number = CMFE_SOLVER_ITERATIVE_GMRES
    ELSEIF (type_string == "SOLVER_ITERATIVE_BiCGSTAB") THEN
      type_number = CMFE_SOLVER_ITERATIVE_BiCGSTAB
    ELSEIF (type_string == "SOLVER_ITERATIVE_CONJGRAD_SQUARED") THEN
      type_number = CMFE_SOLVER_ITERATIVE_CONJGRAD_SQUARED
    !!!types of preconditioners for linear iterative solvers
    ELSEIF (type_string == "SOLVER_ITERATIVE_NO_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_NO_PRECONDITIONER
    ELSEIF (type_string == "SOLVER_ITERATIVE_JACOBI_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_JACOBI_PRECONDITIONER
    ELSEIF (type_string == "SOLVER_ITERATIVE_BLOCK_JACOBI_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_BLOCK_JACOBI_PRECONDITIONER
    ELSEIF (type_string == "SOLVER_ITERATIVE_SOR_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_SOR_PRECONDITIONER
    ELSEIF (type_string == "SOLVER_ITERATIVE_INCOMPLETE_CHOLESKY_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_INCOMPLETE_CHOLESKY_PRECONDITIONER
    ELSEIF (type_string == "SOLVER_ITERATIVE_INCOMPLETE_LU_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_INCOMPLETE_LU_PRECONDITIONER
    ELSEIF (type_string == "SOLVER_ITERATIVE_ADDITIVE_SCHWARZ_PRECONDITIONER") THEN
      type_number = CMFE_SOLVER_ITERATIVE_ADDITIVE_SCHWARZ_PRECONDITIONER
    !! solver libraries
    ELSEIF (type_string == "SOLVER_CMISS_LIBRARY") THEN
      type_number = CMFE_SOLVER_CMISS_LIBRARY
    ELSEIF (type_string == "SOLVER_PETSC_LIBRARY") THEN
      type_number = CMFE_SOLVER_PETSC_LIBRARY
    ELSEIF (type_string == "SOLVER_MUMPS_LIBRARY") THEN
      type_number = CMFE_SOLVER_MUMPS_LIBRARY
    ELSEIF (type_string == "SOLVER_SUPERLU_LIBRARY") THEN
      type_number = CMFE_SOLVER_SUPERLU_LIBRARY
    ELSEIF (type_string == "SOLVER_SPOOLES_LIBRARY") THEN
      type_number = CMFE_SOLVER_SPOOLES_LIBRARY
    ELSEIF (type_string == "SOLVER_UMFPACK_LIBRARY") THEN
      type_number = CMFE_SOLVER_UMFPACK_LIBRARY
    ELSEIF (type_string == "SOLVER_LUSOL_LIBRARY") THEN
      type_number = CMFE_SOLVER_LUSOL_LIBRARY
    ELSEIF (type_string == "SOLVER_ESSL_LIBRARY") THEN
      type_number = CMFE_SOLVER_ESSL_LIBRARY
    ELSEIF (type_string == "SOLVER_LAPACK_LIBRARY") THEN
      type_number = CMFE_SOLVER_LAPACK_LIBRARY
    ELSEIF (type_string == "SOLVER_TAO_LIBRARY") THEN
      type_number = CMFE_SOLVER_TAO_LIBRARY
    ELSEIF (type_string == "SOLVER_HYPRE_LIBRARY") THEN
      type_number = CMFE_SOLVER_HYPRE_LIBRARY
    ELSEIF (type_string == "SOLVER_PASTIX_LIBRARY") THEN
      type_number = CMFE_SOLVER_PASTIX_LIBRARY
    !! jacobain types of Newon Raphson solver
    ELSEIF (type_string == "SOLVER_NEWTON_JACOBIAN_FD_CALCULATED") THEN
      type_number = CMFE_SOLVER_NEWTON_JACOBIAN_FD_CALCULATED
    ELSEIF (type_string == "SOLVER_NEWTON_JACOBIAN_EQUATIONS_CALCULATED") THEN
      type_number = CMFE_SOLVER_NEWTON_JACOBIAN_EQUATIONS_CALCULATED
    ELSEIF (type_string == "SOLVER_NEWTON_JACOBIAN_FD_CALCULATED") THEN
      type_number = CMFE_SOLVER_NEWTON_JACOBIAN_FD_CALCULATED
    ELSE
      CALL HANDLE_ERROR( "Solver parameter " // type_string // " is an invalid solver argument ")
    ENDIF

END FUNCTION


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.READS KEYWORDDS TO DEFINE SOLVER!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION MATCH_CONTROL_LOOP(type_string) RESULT (type_number)
    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                  :: type_number

    IF (type_string == "PROBLEM_CONTROL_SIMPLE_TYPE") THEN
      type_number = CMFE_PROBLEM_CONTROL_SIMPLE_TYPE
    ELSE IF (type_string == "PROBLEM_CONTROL_FIXED_LOOP_TYPE") THEN
      type_number = CMFE_PROBLEM_CONTROL_FIXED_LOOP_TYPE
    ELSE IF (type_string == "PROBLEM_CONTROL_TIME_LOOP_TYPE") THEN
      type_number = CMFE_PROBLEM_CONTROL_TIME_LOOP_TYPE
    ELSE IF (type_string == "PROBLEM_CONTROL_TIME_LOOP_TYPE") THEN
      type_number = CMFE_PROBLEM_CONTROL_TIME_LOOP_TYPE
    ELSE IF (type_string == "PROBLEM_CONTROL_LOAD_INCREMENT_LOOP_TYPE") THEN
      type_number = CMFE_PROBLEM_CONTROL_LOAD_INCREMENT_LOOP_TYPE
    ELSE IF (type_string == "PROBLEM_CONTROL_WHILE_LOOP_TYPE") THEN
      type_number = CMFE_PROBLEM_CONTROL_WHILE_LOOP_TYPE

    ELSE
      CALL HANDLE_ERROR("Invalid control loop argument  "//type_string)
    ENDIF

END FUNCTION

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!! THE FOLLOWING FUNCTION !!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!.READS KEYWORDDS TO DEFINE MATERIALS!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

FUNCTION MATCH_MATERIAL_PARAMETERS(type_string) RESULT (type_number)

    IMPLICIT NONE
    character(*), intent(in) :: type_string
    integer                 :: type_number
    IF (type_string == "EQUATIONS_SET_TRANSVERSE_ISOTROPIC_ACTIVE_SUBTYPE") THEN
      type_number = 5
    ELSE IF (type_string == "EQUATIONS_SET_MOONEY_RIVLIN_SUBTYPE") THEN
       type_number =2
    ELSEIF (type_string == "EQUATIONS_SET_TRANSIENT_NAVIER_STOKES_SUBTYPE")  THEN
      type_number = 2
    ELSE
      CALL HANDLE_ERROR("Invalid material argument "//type_string // "in material_parameter subroutine")

    ENDIF

END FUNCTION MATCH_MATERIAL_PARAMETERS



!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

